### ISSUE TITLE
How to fetch all 100+ data

### ISSUE THREAD

**Issue by AntolKun** [arufars/api-blue-archive#65]
please help! gw mau ambil semua data dari endpoint /api/characters, tapi default 20. itu gimana ya
soalnya fitur endpoint yg paginate gabisa di gw (Laravel 10)

**Comment by arufars** [comment]
@AntolKun pakai ini aja [pagenation](https://github.com/arufars/api-blue-archive?tab=readme-ov-file#get-all-characters-pagination--20-)
